texto = input('Digite algo: ')

print(texto.isupper())
print(texto.islower())
print(texto.isdecimal())
print(texto.isalnum())
print(texto.isascii())
print(texto.isnumeric())
print(texto.isalpha())
print(texto.isspace())
print(texto.isidentifier())
print(texto.istitle())
